// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file seal.colf.

/**
 * Package seal tests all supported data types in various combinations.
 * The generated code for each language is committed into the repository
 * to display and seal the effects of each change.
 */
package seal;
